name: "Build and test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Flake check
        run: nix flake check
      - name: Format check
        run: nix develop --command sh -c 'mill fangshan.checkFormat'
      - name: Build and test
        run: nix run '.#fangshan.verilated'